### ISSUE TITLE
Strikethough not showing up

### ISSUE THREAD

**Issue by scroll-wheel** [mattxwang/howmanyclubsiscrystalin.com#3]
![image](https://user-images.githubusercontent.com/50280292/161487218-9a5c232c-74bc-4246-95b3-4f9a0dc3c1f2.png)
Quick fix: Use `<strike>` instead of `<strikethrough>`. However, if to be semantic, use `<del>` instead of `<strike>`!

**Comment by mattxwang** [comment]
Thanks Alvin! Hm, I think this is actually a problem with the active font; if I apply `<del>`, the resultant font is pretty ugly. I'm just going to remove the 4 entirely.

Eagle eyes, thanks for catching this!

**Comment by mattxwang** [comment]
Closed by [5bf60d3](https://github.com/mattxwang/howmanyclubsiscrystalin.com/commit/5bf60d37f005bffe5333e3b17bf5007a7cf4e7d4)
